package tech.ytsaurus.spyt.gradle.tasks

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.TaskAction

abstract class ProcessPythonFilesTask : DefaultTask() {
    override fun getGroup(): String? {
        return "code generation"
    }

    @get:Input
    abstract val spytScalaVersion: Property<String>

    @get:InputDirectory
    abstract val artifactsPath: DirectoryProperty

    @TaskAction
    fun processFiles() {
        val spytScalaVersion = spytScalaVersion.get()
        val spytPythonVersion = toPythonVersion(spytScalaVersion)

        val versionPyContent = """# This file is autogenerated, don't edit it manually
             |
             |__version__ = "$spytPythonVersion"
             |__scala_version__ = "$spytScalaVersion"
             |""".trimMargin("|")
        val versionPy = artifactsPath.get().file("python/spyt/version.py")
        versionPy.asFile.writeText(versionPyContent)

        val versionJsonContent = """{"scala":"$spytScalaVersion","python":"$spytPythonVersion"}"""
        artifactsPath.get().file("conf/version.json").asFile.writeText(versionJsonContent)
    }

    private fun toPythonVersion(scalaVersion: String): String {
        return when {
            scalaVersion.contains("-alpha-") -> scalaVersion.replace("-alpha-", "a")
            scalaVersion.contains("-beta-") -> scalaVersion.replace("-beta-", "b")
            scalaVersion.contains("-rc-") -> scalaVersion.replace("-rc-", "rc")
            scalaVersion.endsWith("-SNAPSHOT") -> scalaVersion.replace("-SNAPSHOT", "").replace("-", ".dev")
            else -> scalaVersion
        }
    }
}
