SPARK_DISTRIB_ARGS=""
[ "$SPARK_DISTRIB_USE_CACHE" = "true" ] || [ "$SPARK_DISTRIB_OFFLINE" = "true" ] && SPARK_DISTRIB_ARGS+=" --use-cache"
[ "$SPARK_DISTRIB_OFFLINE" = "true" ]   && SPARK_DISTRIB_ARGS+=" --offline"
[ -n "$SPARK_DISTRIB_CACHE_PATH" ]      && SPARK_DISTRIB_ARGS+=" --cache-path $SPARK_DISTRIB_CACHE_PATH"
[ -n "$SPARK_DISTRIB_VERSIONS" ]        && SPARK_DISTRIB_ARGS+=" $SPARK_DISTRIB_VERSIONS"


echo "EXTRA_CONFIG_GENERATOR_OPTIONS = $EXTRA_CONFIG_GENERATOR_OPTIONS"
echo "EXTRA_PUBLISH_CLUSTER_OPTIONS = $EXTRA_PUBLISH_CLUSTER_OPTIONS"
echo "SPARK_DISTRIB_ARGS = $SPARK_DISTRIB_ARGS"

python3.12 -m scripts.config_generator /data $EXTRA_CONFIG_GENERATOR_OPTIONS
python3.12 -m scripts.publish_cluster /data $EXTRA_PUBLISH_CLUSTER_OPTIONS
python3.12 -m scripts.spark_distrib $SPARK_DISTRIB_ARGS
