rootLogger.level=INFO
rootLogger.appenderRef.0.ref=console
rootLogger.appenderRef.1.ref=${env:YT_APPENDER_TITLE:-null}

# Direct log messages to stderr
appender.console.type=Console
appender.console.name=console
appender.console.target=SYSTEM_ERR
appender.console.layout.type=JsonTemplateLayout

# Null appender that ignores log events
appender.null.type=Null
appender.null.name=null

# Log messages to file spark.log for Unified Agent to read
appender.file.type=RollingFile
appender.file.name=file
appender.file.fileName=logs/spark.log
appender.file.filePattern=logs/spark-${env:YT_TASK_NAME:-workers}-%d{yyyy-MM-dd}.%i.log.gz
appender.file.append=true
appender.file.layout.type=JsonTemplateLayout
appender.file.layout.eventTemplateUri=classpath:unified-agent-template.json

appender.file.layout.eventTemplateAdditionalField[0].type=EventTemplateAdditionalField
appender.file.layout.eventTemplateAdditionalField[0].key=component
appender.file.layout.eventTemplateAdditionalField[0].value=${env:YT_TASK_NAME}
appender.file.layout.eventTemplateAdditionalField[0].format=STRING

appender.file.layout.eventTemplateAdditionalField[1].type=EventTemplateAdditionalField
appender.file.layout.eventTemplateAdditionalField[1].key=operation_alias
appender.file.layout.eventTemplateAdditionalField[1].value=${env:YT_OPERATION_ALIAS}
appender.file.layout.eventTemplateAdditionalField[1].format=STRING

appender.file.layout.eventTemplateAdditionalField[2].type=EventTemplateAdditionalField
appender.file.layout.eventTemplateAdditionalField[2].key=app_alias
appender.file.layout.eventTemplateAdditionalField[2].value=${sys:spark.metrics.conf.*.sink.solomon.app_alias}
appender.file.layout.eventTemplateAdditionalField[2].format=STRING

# Set the default spark-shell log level to WARN. When running the spark-shell, the
# log level for this class is used to overwrite the root logger's log level, so that
# the user can have different defaults for the shell and regular Spark apps.
logger.repl.name=org.apache.spark.repl.Main
logger.repl.level=warn

# Settings to quiet third party logs that are too verbose
logger.jetty1.name=org.sparkproject.jetty
logger.jetty1.level=warn
logger.jetty2.name=org.sparkproject.jetty.util.component.AbstractLifeCycle
logger.jetty2.level=error
logger.repl_expr_typer.name=org.apache.spark.repl.SparkIMain$exprTyper
logger.repl_expr_typer.level=info
logger.repl_loop_interpreter.name=org.apache.spark.repl.SparkILoop$SparkILoopInterpreter
logger.repl_loop_interpreter.level=info
logger.parquet1.name=org.apache.parquet
logger.parquet1.level=error
logger.parquet2.name=parquet
logger.parquet2.level=error

# SPARK-9183: Settings to avoid annoying messages when looking up nonexistent UDFs in SparkSQL with Hive support
logger.RetryingHMSHandler.name=org.apache.hadoop.hive.metastore.RetryingHMSHandler
logger.RetryingHMSHandler.level=fatal
logger.FunctionRegistry.name=org.apache.hadoop.hive.ql.exec.FunctionRegistry
logger.FunctionRegistry.level=error

logger.spyt_launcher.name=tech.ytsaurus.spark.launcher
logger.spyt_launcher.level=debug
logger.spyt_launcher.appenderRef.0.ref=console
logger.spyt_launcher.additivity=false

logger.spark.name=org.apache.spark
logger.spark.level=info
logger.spark.appenderRef.0.ref=console
logger.spark.appenderRef.1.ref=${env:YT_APPENDER_TITLE:-null}
